# Copyright 2013, Qualcomm Innovation Center, Inc.
#
#    All rights reserved.
#    This file is licensed under the 3-clause BSD license in the NOTICE.txt
#    file for this project. A copy of the 3-clause BSD license is found at:
#
#        http://opensource.org/licenses/BSD-3-Clause.
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the license is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the license for the specific language governing permissions and
#    limitations under the license.

Import('env')

# Build the test programs on win32/linux
if env['TARG'] == 'win32' or env['TARG'] == 'linux':
    env.Program('mutter', ['mutter.c'] + env['aj_obj'])
    env.Program('ajlite', ['ajlite.c'] + env['aj_obj'])
    env.Program('aestest', ['aestest.c'] + env['aj_obj'])
    env.Program('aesbench', ['aesbench.c'] + env['aj_obj'])
    env.Program('svclite', ['svclite.c'] + env['aj_obj'])
    env.Program('clientlite', ['clientlite.c'] + env['aj_obj'])
    env.Program('siglite', ['siglite.c'] + env['aj_obj'])
    env.Program('sessions', ['sessions.c'] + env['aj_obj'])
    env.Program('nvramtest', ['nvramtest.c'] + env['aj_obj'])
    env.Program('bastress2', ['bastress2.c'] + env['aj_obj'])