# Copyright 2013, Qualcomm Innovation Center, Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

Import('env')

# Build the test programs on win32/linux
if env['TARG'] == 'win32' or env['TARG'] == 'linux' or env['TARG'] == 'yield-linux':
    env.Program('mutter', ['mutter.c'] + env['aj_obj'])
    env.Program('ajlite', ['ajlite.c'] + env['aj_obj'])
    env.Program('aestest', ['aestest.c'] + env['aj_obj'])
    env.Program('aesbench', ['aesbench.c'] + env['aj_obj'])
    env.Program('svclite', ['svclite.c'] + env['aj_obj'])
    env.Program('clientlite', ['clientlite.c'] + env['aj_obj'])
    env.Program('siglite', ['siglite.c'] + env['aj_obj'])
    env.Program('sessions', ['sessions.c'] + env['aj_obj'])

