# Copyright 2013, Qualcomm Innovation Center, Inc.
#
#    All rights reserved.
#    This file is licensed under the 3-clause BSD license in the NOTICE.txt
#    file for this project. A copy of the 3-clause BSD license is found at:
# 
#         http://opensource.org/licenses/BSD-3-Clause.
# 
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the license is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the license for the specific language governing permissions and
#     limitations under the license.

Import('env')

# Add/remove projects from build

# Only build the following samples for the TARG operating system.
# The samples/examples for target platforms are handled by
# the target specific directory (viz. target/arduino).
if env['TARG'] == 'win32' or env['TARG'] == 'linux':
    env.SConscript(['basic/SConscript'])
    env.SConscript(['secure/SConscript'])
