# Copyright 2013, Qualcomm Innovation Center, Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#

Import('env')

# Add/remove projects from build

# Only build the following samples for the TARG operating system.
# The samples/examples for target platforms are handled by
# the target specific directory (viz. target/arduino).
if env['TARG'] == 'win32' or env['TARG'] == 'linux':
    env.SConscript(['basic/SConscript'])
    env.SConscript(['secure/SConscript'])
